name: Run Playwright Java Tests with Extent Report

on:
  workflow_dispatch:
    inputs:
      testTarget:
        description: 'Select the test class to run'
        required: true
        default: 'com.cicdtest.pom.Test.LoginTest'
        type: choice
        options:
          - com.cicdtest.pom.Test.LoginTest
          - com.cicdtest.pom.Test.AddProductTest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Playwright
        run: |
          npm install -g playwright
          playwright install

      - name: Give permission to gradlew
        run: chmod +x ./gradlew

      - name: Run Selected Test Class with Gradle
        run: ./gradlew clean test --tests "${{ github.event.inputs.testTarget }}"

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: target/test-logs/extent-report.html  # Update if needed
